name: Node.js
on:
  push:
    branches: [ main ]
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
    
    - name: Use Node.js 15.12.0
      uses: actions/setup-node@v1
      with:
        node-version: 15.12.0
      id: node
    
    - name: Checkout code
      uses: actions/checkout@v2
   
    - name: Test
      run: node ./temp/
