name: Temporary Client
on:
  push:
    branches:
      - main
    # paths:
    #   - temp/src/**
    
jobs:
  build:
    name: Build & Deploy
    runs-on: self-hosted
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
    
      - name: Install Node
        uses: actions/setup-node@v1
        with:
          node-version: 14
          yarn: 1.22.4

      - name: Change into project directory
        run: cd /var/www/xiubox
      
      - name: Pull updates
        run: git pull origin main

      - name: Restart server
        run: cd temp && yarn && yarn restart