name: Temporary Client
on:
  push:
    branches:
      - main
    # paths:
    #   - temp/src/**
    
jobs:
  build:
    name: Deploy
    runs-on: self-hosted
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
    
      - name: Install node and yarn
        uses: actions/setup-node@v1
        with:
          node-version: 14
          yarn: 1.22.4

      - name: Restart server
        run: cd temp && yarn && yarn restart
